"""migration6

Revision ID: 173cedd4a054
Revises: 9c035dd38c4e
Create Date: 2022-03-07 17:23:08.054208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '173cedd4a054'
down_revision = '9c035dd38c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('confirmed', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
