"""migration21

Revision ID: 36ff2cd6bb3a
Revises: 8f12f5f25219
Create Date: 2022-03-25 13:56:14.934111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ff2cd6bb3a'
down_revision = '8f12f5f25219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('urban_sports_membership_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'urban_sports_membership_no')
    # ### end Alembic commands ###
