"""migration26

Revision ID: 64cfe1a3a218
Revises: 810056b8ac59
Create Date: 2022-04-02 06:45:21.775959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64cfe1a3a218'
down_revision = '810056b8ac59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('venue_type', sa.String(), nullable=True))
    op.drop_column('venue', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('venue', 'venue_type')
    # ### end Alembic commands ###
