"""migration25

Revision ID: 810056b8ac59
Revises: a8ed3cc306ba
Create Date: 2022-04-02 06:43:10.799471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810056b8ac59'
down_revision = 'a8ed3cc306ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'type')
    # ### end Alembic commands ###
