"""migration3

Revision ID: 9c035dd38c4e
Revises: f86d69d716e4
Create Date: 2022-03-07 16:48:13.522375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c035dd38c4e'
down_revision = 'f86d69d716e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'status')
    # ### end Alembic commands ###
