"""migration23

Revision ID: a8ed3cc306ba
Revises: 36ff2cd6bb3a
Create Date: 2022-03-25 14:25:34.493409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ed3cc306ba'
down_revision = '36ff2cd6bb3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('street', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'street')
    # ### end Alembic commands ###
