"""migration17

Revision ID: bf9307a47982
Revises: 145afaffce8a
Create Date: 2022-03-12 11:59:18.386929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf9307a47982'
down_revision = '145afaffce8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reservation_created_at', table_name='reservation')
    op.drop_table('reservation')
    op.add_column('booking', sa.Column('earliest_ticket_datetime', sa.DateTime(), nullable=True))
    op.drop_column('booking', 'earliest_reservation_datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('earliest_reservation_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('booking', 'earliest_ticket_datetime')
    op.create_table('reservation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name='reservation_booking_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='reservation_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reservation_pkey')
    )
    op.create_index('ix_reservation_created_at', 'reservation', ['created_at'], unique=False)
    # ### end Alembic commands ###
