"""migration27

Revision ID: e81c44ad23e9
Revises: 64cfe1a3a218
Create Date: 2022-04-05 18:30:00.755955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81c44ad23e9'
down_revision = '64cfe1a3a218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('house_no', sa.String(), nullable=True))
    op.add_column('user', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_column('user', 'city')
    op.drop_column('user', 'postal_code')
    op.drop_column('user', 'house_no')
    op.drop_column('user', 'birthday')
    # ### end Alembic commands ###
