"""migration2

Revision ID: f86d69d716e4
Revises: 9ea181100bdc
Create Date: 2022-03-07 15:21:38.632071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f86d69d716e4'
down_revision = '9ea181100bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('confirmation_code', sa.String(), nullable=True))
    op.drop_column('reservation', 'confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('confirmed', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('booking', 'confirmation_code')
    # ### end Alembic commands ###
